#
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
#
#server configuration
server.address=0.0.0.0
server.port=8090

cxf.path=/rest

# logging.level.org.jbpm.services.task.deadlines.notifications=debug
# logging.level.com.icegreen=trace

#kie server config
kieserver.serverId=business-application-service
kieserver.serverName=business-application-service
kieserver.location=http://localhost:8090/rest/server
#kieserver.controllers=


#kie server capabilities
kieserver.drools.enabled=true
kieserver.dmn.enabled=true
kieserver.jbpm.enabled=true
kieserver.jbpmui.enabled=true
kieserver.casemgmt.enabled=true
#kieserver.prometheus.enabled=true

# 推荐：使用 Demo 模式（不实际调用链上合约）
blockchain.enabled=false



#jbpm configuration
jbpm.executor.enabled=false
#jbpm.executor.retries=5
#jbpm.executor.interval=3
#jbpm.executor.threadPoolSize=1
#jbpm.executor.timeUnit=SECONDS


#data source configuration
spring.datasource.username=ccjbpmusr
spring.datasource.password=ccjbpmpass
spring.datasource.url=jdbc:mysql://localhost:3306/cc_jbpm_db?&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.jdbc.jdbc2.optional.MysqlXADataSource


#hibernate configuratio
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.entity-scan-packages=com.company.models*

#banner
spring.banner.location=classpath:banner.txt

springdoc.swagger-ui.path=/swagger-ui.html

narayana.transaction-manager-id=1
narayana.default-timeout=120
narayana.dbcp.enabled=true

# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/template/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# JWT configuration
collectorcoin.app.jwtSecret= CollectorCoinSecretKey
collectorcoin.app.jwtExpirationMs=86400000

# Blockchain Configuration
# blockchain.network.url=https://sepolia.infura.io/v3/10420528bdce4008b710f7ffd2994413
blockchain.network.url=http://127.0.0.1:8545

# Admin wallet private key
# blockchain.admin.private.key=0xea6c44ac03bff858b476bba40716402b03e41b8e97e276d1baec7c37d42484a0

# Contract addresses
#blockchain.contract.token.address=0xE109d1176B4c7C3Fa53b897C669AA5fB5Ab20a11 // deployed on sepolia -- original values
#blockchain.contract.factory.address=0x379eae4847bdf385641faefE2a5C5A671A69c997 // deployed on sepolia -- original values

# Contract addresses - new hardhat values
# blockchain.contract.token.address=0x5FbDB2315678afecb367f032d93F642f64180aa3
# blockchain.contract.factory.address=0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512


// 私钥钱包
blockchain.admin.private.key=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
blockchain.contract.token.address=0x5FbDB2315678afecb367f032d93F642f64180aa3
blockchain.contract.factory.address=0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512