// User Actions
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOGOUT = "LOGOUT";

// Message Actions
const SET_MESSAGE = "SET_MESSAGE";
const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// Project Listings Actions
const RETRIEVE_PROJECT_LISTINGS = "RETRIEVE_PROJECT_LISTINGS";
const ALL_LISTINGS = "ALL_LISTINGS";
const ALL_BID_LISTINGS = "ALL_BID_LISTINGS";
const SELECT_BID_LISTING = "SELECT_BID_LISTING";
const UPDATE_BID_LISTING = "UPDATE_BID_LISTING";
const GET_PROJECT_LISTING_BY_USERNAME = "GET_PROJECT_LISTING_BY_USERNAME";
const CREATE_PROJECT_LISTING = "CREATE_PROJECT_LISTING";
const CREATE_BID_LISTING_BY_BIDDERID = "CREATE_BID_LISTING_BY_BIDDERID";
const CREATE_PROJECT_LISTING_BY_USERNAME = "CREATE_PROJECT_LISTING_BY_USERNAME";
const UPDATE_PROJECT_LISTING = "UPDATE_PROJECT_LISTING";
const DELETE_ALL_PROJECT_LISTINGS = "DELETE_ALL_PROJECT_LISTINGS";
const DELETE_PROJECT_LISTINGS_BY_USER = "DELETE_PROJECT_LISTINGS_BY_USER";
const DELETE_PROJECT_BY_ID = "DELETE_PROJECT_BY_ID";
const UPDATE_PROJECT_LISTING_BY_ID = "UPDATE_PROJECT_LISTING_BY_ID";

// Investment Actions
const GET_INVESTMENT_BY_USERID = "GET_INVESTMENT_BY_USERID";
const CREATE_INVESTMENT_BY_USERID = "CREATE_INVESTMENT_BY_USERID";

// Aution actions
const ALL_AUCTION_BID_LISTINGS = "ALL_AUCTION_BID_LISTINGS";
const SELECT_AUCTION_BID_LISTING = "SELECT_AUCTION_BID_LISTING";
const UPDATE_AUCTION_BID_LISTING = "UPDATE_AUCTION_BID_LISTING";
const CREATE_AUCTION_BID_LISTING_BY_BUYERID =
  "CREATE_AUCTION_BID_LISTING_BY_BUYERID";

module.exports = {
  REGISTER_SUCCESS,
  REGISTER_FAIL,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  LOGOUT,
  SET_MESSAGE,
  CLEAR_MESSAGE,
  RETRIEVE_PROJECT_LISTINGS,
  ALL_LISTINGS,
  ALL_BID_LISTINGS,
  SELECT_BID_LISTING,
  UPDATE_BID_LISTING,
  GET_PROJECT_LISTING_BY_USERNAME,
  CREATE_PROJECT_LISTING,
  CREATE_BID_LISTING_BY_BIDDERID,
  CREATE_PROJECT_LISTING_BY_USERNAME,
  UPDATE_PROJECT_LISTING,
  DELETE_ALL_PROJECT_LISTINGS,
  DELETE_PROJECT_LISTINGS_BY_USER,
  DELETE_PROJECT_BY_ID,
  UPDATE_PROJECT_LISTING_BY_ID,
  GET_INVESTMENT_BY_USERID,
  CREATE_INVESTMENT_BY_USERID,
  ALL_AUCTION_BID_LISTINGS,
  SELECT_AUCTION_BID_LISTING,
  UPDATE_AUCTION_BID_LISTING,
  CREATE_AUCTION_BID_LISTING_BY_BUYERID,
};
